### ISSUE TITLE
React Native Styles?

### ISSUE THREAD

**Issue by Noitidart** [react-component/m-picker#20]
Hi there,
I am working on a react native project. I was using the Picker component - https://facebook.github.io/react-native/docs/picker.html - however I hit the limit of not being able to style the dividing borders and the alignment of the text in the <Item> (I was hoping for left alignment). Is this possible with your component?

**Comment by silentcloud** [comment]
@Noitidart you can try`itemStyle` property.

**Comment by Noitidart** [comment]
Thanks very much @silentcloud it turned out that `itemStyle` property was iOS only. :(

**Comment by silentcloud** [comment]
@Noitidart Also support android.

https://github.com/react-component/m-picker/blob/master/src/NativePicker.android.tsx#L122

**Comment by Noitidart** [comment]
Ah no way. So the official component only supports itemStyle with iOS, but this component supports itemStyle with both! I will test this out thank you!
