### ISSUE TITLE
样例跑不起来

### ISSUE THREAD

**Issue by chris-cai** [react-component/m-picker#30]
![image](https://user-images.githubusercontent.com/14368013/27618820-17d82a00-5bf1-11e7-862c-0077d9d61c09.png)
![image](https://user-images.githubusercontent.com/14368013/27618834-2a288010-5bf1-11e7-8255-ca665842110d.png)
请帮忙看下什么问题 

引入文件
![image](https://user-images.githubusercontent.com/14368013/27618862-46ffc540-5bf1-11e7-89c9-eb8c3b81141a.png)

**Comment by silentcloud** [comment]
你直接贴一下代码吧 @chris-cai

**Comment by chris-cai** [comment]
import 'rmc-picker/assets/index.css'
import 'rmc-picker/assets/popup.css'
import * as Picker from 'rmc-picker/lib/Picker'
import * as MultiPicker from 'rmc-picker/lib/MultiPicker';
import * as Popup from 'rmc-picker/lib/Popup'

let count = 0;
const len = 10;


/**
 * 单滚轮
 */

class SingleWheelEmitter extends React.Component<any, any> {
   state =  {
    disabled: false,
    items: this.getItems(count),
    value: `${count}`,
  };

  onChange = (value) => {
    console.log('onChange', value);
    this.setState({
      value,
    });
  }

  disable = () => {
    this.setState({
      disabled: !this.state.disabled,
    });
  }

  getItems(start) {
    const items: any[] = [];
    for (let i = start; i < start + len; i++) {
      items.push(<div key={i}>i</div>);
    }
    return items;
  }

  rerender = () => {
    count += len;
    const items = this.getItems(count);
    this.setState({
      items,
      value: String(count),
    });
  }

  render() {
    return (
      <div style={{ background: '#f5f5f9', padding: 10 }}>
        <button onClick={this.rerender}>rerender</button>
        &nbsp;
        <button onClick={this.disable}>{this.state.disabled ? 'enable' : 'disable'}</button>
        <Picker
          selectedValue={this.state.value}
          disabled={this.state.disabled}
          onValueChange={this.onChange}
        >
          {this.state.items}
        </Picker>
      </div>
    );
  }
}

export default SingleWheelEmitter

**Comment by chris-cai** [comment]
`
import 'rmc-picker/assets/index.css'
import 'rmc-picker/assets/popup.css'
import * as Picker from 'rmc-picker/lib/Picker'
import * as MultiPicker from 'rmc-picker/lib/MultiPicker';
import * as Popup from 'rmc-picker/lib/Popup'

let count = 0;
const len = 10;


/**
 * 单滚轮
 */

class SingleWheelEmitter extends React.Component<any, any> {
   state =  {
    disabled: false,
    items: this.getItems(count),
    value: `${count}`,
  };

  onChange = (value) => {
    console.log('onChange', value);
    this.setState({
      value,
    });
  }

  disable = () => {
    this.setState({
      disabled: !this.state.disabled,
    });
  }

  getItems(start) {
    const items: any[] = [];
    for (let i = start; i < start + len; i++) {
      items.push(<div key={i}>i</div>);
    }
    return items;
  }

  rerender = () => {
    count += len;
    const items = this.getItems(count);
    this.setState({
      items,
      value: String(count),
    });
  }

  render() {
    return (
      <div style={{ background: '#f5f5f9', padding: 10 }}>
        <button onClick={this.rerender}>rerender</button>
        &nbsp;
        <button onClick={this.disable}>{this.state.disabled ? 'enable' : 'disable'}</button>
        <Picker
          selectedValue={this.state.value}
          disabled={this.state.disabled}
          onValueChange={this.onChange}
        >
          {this.state.items}
        </Picker>
      </div>
    );
  }
}

export default SingleWheelEmitter`

**Comment by chris-cai** [comment]
import 'rmc-picker/assets/index.css'
import 'rmc-picker/assets/popup.css'
import * as Picker from 'rmc-picker/lib/Picker'
import * as MultiPicker from 'rmc-picker/lib/MultiPicker';
import * as Popup from 'rmc-picker/lib/Popup'

let count = 0;
const len = 10;


/**
 * 单滚轮
 */

class SingleWheelEmitter extends React.Component<any, any> {
   state =  {
    disabled: false,
    items: this.getItems(count),
    value: `${count}`,
  };

  onChange = (value) => {
    console.log('onChange', value);
    this.setState({
      value,
    });
  }

  disable = () => {
    this.setState({
      disabled: !this.state.disabled,
    });
  }

  getItems(start) {
    const items: any[] = [];
    for (let i = start; i < start + len; i++) {
      items.push(<div key={i}>i</div>);
    }
    return items;
  }

  rerender = () => {
    count += len;
    const items = this.getItems(count);
    this.setState({
      items,
      value: String(count),
    });
  }

  render() {
    return (
      <div style={{ background: '#f5f5f9', padding: 10 }}>
        <button onClick={this.rerender}>rerender</button>
        &nbsp;
        <button onClick={this.disable}>{this.state.disabled ? 'enable' : 'disable'}</button>
        <Picker
          selectedValue={this.state.value}
          disabled={this.state.disabled}
          onValueChange={this.onChange}
        >
          {this.state.items}
        </Picker>
      </div>
    );
  }
}

export default SingleWheelEmitter

**Comment by silentcloud** [comment]
@chris-cai 你用的版本是好多，如果是 3.10.x 的话 看这个 demo

https://github.com/react-component/m-picker/blob/3.10.7/examples/picker.tsx

如果是 4.x beta 版本，就看 master 里的
