### ISSUE TITLE
Web example for picker.popup has no items

### ISSUE THREAD

**Issue by Noitidart** [react-component/m-picker#31]
For the online example of the picker.popup - http://react-component.github.io/m-picker/examples/popup.html

It is not showing any items. Here is screenshot for me:

![http://i.imgur.com/WCiSZkl.png](http://i.imgur.com/WCiSZkl.png)

**Comment by silentcloud** [comment]
@Noitidart it's ok, we only pass `<div>ok</div>` to `content` prop

![image](https://user-images.githubusercontent.com/1698185/27625487-627009d6-5c17-11e7-9e06-7eea47a39b63.png)

**Comment by paranoidjk** [comment]
@silentcloud This demo is too poor...

**Comment by Noitidart** [comment]
Thanks very much for the update! It seems that "ok" now shows "content" and has some padding. I don't know but I was expecting to see picking list(s) of items. This is what I see now:

![](http://i.imgur.com/7iqKDwa.png)

**Comment by paranoidjk** [comment]
@Noitidart content is which for you to custom, see https://mobile.ant.design/components/picker

**Comment by Noitidart** [comment]
Ohhhh I get it now!! I just stick in a picker or a multipicker into the popup! Super duper cool. Thank you sir!
