### ISSUE TITLE
MultiPicker logic incorrect, when not set selectedValue.

### ISSUE THREAD

**Issue by zhang740** [react-component/m-picker#32]
If not set selectedValue, is no has event fire when reselect the first item.

core code:

MultiPicker.tsx:
```js
    const selectedValue = this.getValue();
    const colElements = React.Children.map(children, (col: any, i) => {
      return React.cloneElement(col, {
        selectedValue: selectedValue[i],
        onValueChange: (...args) => this.onValueChange(i, ...args),
      });
    });
```

the `getValue` implement in MultiPickerMixin.tsx:
```js
  getValue() {
    const { children, selectedValue } = this.props;
    if (selectedValue && selectedValue.length) {
      return selectedValue;
    } else {
      if (!children) {
        return [];
      }
      return React.Children.map(children, (c: any) => {
        const cc: any = React.Children.toArray(c.props.children);
        return cc && cc[0] && cc[0].props.value;
      });
    }
  },
```

If not set selectedValue, the result of `getValue()` alway equel the first item's `value` of picker's children of multipicker.

**Comment by paranoidjk** [comment]
What's your problem?

Can you give a reproducible demo?

**Comment by zhang740** [comment]
selectedValue is required for MultiPicker.

**Comment by paranoidjk** [comment]
@zhang740 If so, consider add a dev console warning about requirement props check, eg: https://github.com/react-component/tabs/blob/7f78a1668fb034e9cc85b62d19df4e9ce1c516ee/src/TabBarMixin.js#L38
