### ISSUE TITLE
Not snap in Android

### ISSUE THREAD

**Issue by hungdev** [react-component/m-picker#38]
It does not snap in Android.
<img width="364" alt="screen shot 2017-09-07 at 2 45 55 pm" src="https://user-images.githubusercontent.com/12009276/30151876-78073d54-93db-11e7-8814-00de5435aaf7.png">

**Comment by silentcloud** [comment]
Fixed  in https://github.com/react-component/m-picker/commit/1c39f881e4d752fda7b90da5a42e2d70735af758
